# Generated by Django 4.0.3 on 2022-03-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Publicado'),
        ),
    ]
